# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="gentoo"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git textmate ruby)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

aliases() {
  if [ -d "/home/vagrant/code/platform/$1" ]; then
    cd "/home/vagrant/code/platform/$1"
  else
    cd "/Users/Salrepe/peertransfer/code/platform/$1"
  fi
}

alias core='aliases apps/core'
alias operations='aliases apps/operations'
alias payschool='aliases apps/payschool'
alias dashboard='aliases apps/dashboards'
alias hedge_oanda='aliases apps/hedge_oanda'
alias salesforce='aliases apps/salesforce'
alias filer='aliases apps/filer'
alias api='aliases apps/api'
alias exchange='aliases apps/exchange'
alias messages='aliases apps/messages'
alias baywatch='aliases apps/baywatch'
alias webhook='aliases apps/webhook'
alias watchlist='aliases apps/watchlist_lexisnexis'
alias lounge='aliases apps/lounge'
alias health_manager='aliases apps/health_manager'
alias cookbooks='aliases infra/cookbooks'
alias bank_router='aliases apps/bank_router'
alias board='aliases apps/peerboard'
alias collector='aliases apps/processor_collector'
alias platform='aliases'
alias infra='aliases infra'
alias redisstart='sudo launchctl start io.redis.redis-server'
alias redisstop='sudo launchctl stop io.redis.redis-server'
alias goodies="cd ~/code/platform/libs/peertransfer_goodies"
alias motherme="ssh salva@mother.peertransfer.me"
alias mothercom="ssh salva@mother.peertransfer.com"
alias ber="bundle exec rspec"
alias be="bundle exec"

export OPSCODE_USER='salrepe'
export VAGRANT_ENVIRONMENT='vagrant'
export OPSCODE_ORGNAME='peertransfer'
export VAGRANT_HOSTNAME="$OPSCODE_USER-$VAGRANT_ENVIRONMENT"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:/usr/local/sbin
PATH=$PATH:/Users/salva/.rvm/gems/ree-1.8.7-2011.03/gems/rhc-0.92.11/bin
export PATH="$HOME/.rbenv/bin:$PATH"

export PTCODE=/Volumes/code
export PATH="$HOME/.rbenv/bin:$PATH"
source ~/.fresh/build/shell.sh
export EDITOR='vim'
export PT_VM_MEMORY=4096

#Remove git status check from prompt
function git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$ZSH_THEME_GIT_PROMPT_SUFFIX"
}
eval "$(rbenv init -)"
